#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend robertnjoroge-frontend
        bind *:80
        mode http
        default_backend robertnjoroge-backend
backend robertnjoroge-backend
        balance roundrobin
        server 124951-web-01 54.88.65.48:80 check
        server 124951-web-02 54.210.52.145:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
